name: build-deploy-azure-app
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      
      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore Nuget packages
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build
     
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Docker Image and push to Docker Hub
        uses: docker/build-push-action@v2.9.0
        with:
          push: true
          tags: production/recipeappenv:latest

#   Not sure if needed
#      - name: Publish
#        run: dotnet publish FullStackRecipeApp/FullStackRecipeApp.csproj -c Release -o website
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: app
#          path: website/**
#          if-no-files-found: error
